name: AutoBuild .NET

on: [push, pull_request, workflow_dispatch]

jobs:
  build-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build CustomCosmetics/CustomCosmetics.csproj \
            --configuration Release \
            --output ./build-output

      - name: Create zip
        run: |
          mkdir -p ./artifact-output
          cd ./build-output
          zip -r ../artifact-output/CustomCosmetics-${{ github.ref_name }}.zip .

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: CustomCosmetics-${{ github.ref_name }}
          path: ./artifact-output/CustomCosmetics-${{ github.ref_name }}.zip

      - name: Cleanup
        run: |
          rm -rf ./build-output
          rm -rf ./artifact-output
        if: always()